### ISSUE TITLE
container: borgmatic

### ISSUE THREAD

**Issue by ThatisMyGitHub** [ajnart/dcm#10]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

docker-borgmatic

### Display Name

borgmatic

### Description

Containerized stack to easily manage backups with BorgBackup

### Category

Security

### Tags

Monitoring, Backup, UI, Integration, Automation

### GitHub URL (Optional)

https://github.com/borgmatic-collective/docker-borgmatic

### Docker Compose Service Definition

```yaml
services:
  borgmatic:
    container_name: borgmatic
    image: ghcr.io/borgmatic-collective/borgmatic
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /home:/mnt/source:ro
      - ./data/repository:/mnt/borg-repository
      - ./data/borgmatic.d:/etc/borgmatic.d/
      - ./data/.config/borg:/root/.config/borg
      - ./data/.ssh:/root/.ssh
      - ./data/.cache/borg:/root/.cache/borg
      - ./data/.state/borgmatic:/root/.local/state/borgmatic
    restart: ${RESTART_POLICY}
```
