### ISSUE TITLE
container: NetAlertX

### ISSUE THREAD

**Issue by jokob-sk** [ajnart/dcm#11]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

netalertx

### Display Name

NetAlertX 

### Description

Network intruder and presence detector. Scans for devices connected to your network and alerts you if new and unknown devices are found.

### Category

Media

### Tags

Monitoring, Security, Network

### GitHub URL (Optional)

https://github.com/jokob-sk/NetAlertX

### Docker Compose Service Definition

```yaml
services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest" 
    image: "ghcr.io/jokob-sk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - local_path/config:/app/config
      - local_path/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - local_path/logs:/app/log
      # (API: OPTION 1) use for performance
      - type: tmpfs
        target: /app/api
      # (API: OPTION 2) use when debugging issues 
      # -  local_path/api:/app/api
    environment:
      - TZ=${TZ}      
      - PORT=20211
```
