### ISSUE TITLE
container: Gluetun VPN client

### ISSUE THREAD

**Issue by hitafer** [ajnart/dcm#12]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

gluetun

### Display Name

Gluetun VPN client

### Description

Lightweight swiss-army-knife-like VPN client to multiple VPN service providers

### Category

Security

### Tags

Privacy, Security

### GitHub URL (Optional)

https://github.com/qdm12/gluetun

### Docker Compose Service Definition

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
    volumes:
      - /yourpath:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
```
