### ISSUE TITLE
container: Actual Budget

### ISSUE THREAD

**Issue by Codycody31** [ajnart/dcm#14]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

actual-budget

### Display Name

Actual Budget

### Description

A local-first personal finance app

### Category

Other (specify in additional information)

### Tags

Money

### GitHub URL

https://github.com/actualbudget/actual

### Icon URL

 https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/actual-budget.svg

### Docker Compose Service Definition

```yaml
services:
  actual-budget:
    container_name: ${CONTAINER_PREFIX}actual-budget
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    volumes:
      - ${DATA_PATH}/actual-budget:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: ${RESTART_POLICY}
```

### Additional Information

Probably a better category would be personal management or something along the lines of that.
