### ISSUE TITLE
container: Sonarr

### ISSUE THREAD

**Issue by BlackLucifer66** [ajnart/dcm#16]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

sonarr

### Display Name

Sonarr

### Description

Test

### Category

Media

### Tags

TV, PVR, Monitoring

### GitHub URL

https://github.com/sonarr

### Docker Compose Service Definition

```yaml
services:
  sonarr:
    container_name: ${CONTAINER_PREFIX}sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/tv:/data/tv
      - ${DATA_PATH}/downloads:/data/downloads
    restart: ${RESTART_POLICY}
```
