### ISSUE TITLE
container: iSponsorBlockTV

### ISSUE THREAD

**Issue by dmunozv04** [ajnart/dcm#18]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

isponsorblocktv

### Display Name

iSponsorBlockTV

### Description

SponsorBlock client for YouTube TV, allows skipping sponsors, muting and skipping ads.

### Category

Media

### Tags

TV, Automation, YouTube

### GitHub URL

https://github.com/dmunozv04/iSponsorBlockTV

### Icon URL

 https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/youtube.svg

### Docker Compose Service Definition

```yaml
services:
  isponsorblocktv:
    container_name: ${CONTAINER_PREFIX}isponsorblocktv
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${DATA_PATH}/isponsorblocktv:/app/data
    restart: ${RESTART_POLICY}
```

### Additional Information

I'm the project maintainer, this docker compose is taken from the recommended docker compose on the repo wiki.

PS: this project is really cool, thanks for taking the time to make it
