### ISSUE TITLE
container: Mediacms

### ISSUE THREAD

**Issue by JamyangTech** [ajnart/dcm#22]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

mediacms

### Display Name

Mediacms

### Description

A self-hosted YouTube type service for video streaming

### Category

Media

### Tags

Streaming, Self-host

### GitHub URL

https://github.com/mediacms-io/mediacms

### Docker Compose Service Definition

```yaml
services:
  sonarr:
    container_name: ${CONTAINER_PREFIX}sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/tv:/data/tv
      - ${DATA_PATH}/downloads:/data/downloads
    restart: ${RESTART_POLICY}
```

### Additional Information

Apologies my own technical knowledge is very limited, I have been trying to launch MediaCMS from unraid and thought I'd submit it in case others are trying to do the same
