### ISSUE TITLE
container: Calibre-Web Automated

### ISSUE THREAD

**Issue by gelbphoenix** [ajnart/dcm#28]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

calibre-web-automated

### Display Name

Calibre-Web Automated

### Description

Calibre-Web but automated and with Calibre features! Fully automate and simplify your eBook set up!

### Category

Media

### Tags

eBooks, Reading, Library, Automation

### GitHub URL

https://github.com/crocodilestick/Calibre-Web-Automated

### Icon URL

https://raw.githubusercontent.com/crocodilestick/Calibre-Web-Automated/refs/heads/main/README_images/cwa-logo-round-dark.png

### Docker Compose Service Definition

```yaml
services:
  calibre-web-automated:
    container_name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/config:/config 
      - ${CONFIG_PATH}/ingest:/cwa-book-ingest
      - ${DATA_PATH}/calibre/library:/calibre-library 
    ports:
      - 8083:8083 
    restart: ${RESTART_POLICY}
```

### Additional Information

The definition is directly from the [project](https://github.com/crocodilestick/Calibre-Web-Automated). I personally only have removed the comments that are in the example.
