### ISSUE TITLE
librephotos

### ISSUE THREAD

**Issue by dft601** [ajnart/dcm#29]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

librephotos

### Display Name

librephotos

### Description

LibrePhotos is a self-hosted photo management application, designed as a privacy-respecting alternative to Google Photos. It lets you store, organize, and browse your photos on your own server, NAS, or home setup—without relying on any cloud provider.

### Category

Database

### Tags

Photo

### GitHub URL

https://github.com/LibrePhotos/librephotos

### Docker Compose Service Definition

```yaml
services:
  dontknow:
    container_name: ${CONTAINER_PREFIX}dontknow
    image: dontknow:latest
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    restart: ${RESTART_POLICY}
```

### Additional Information

sorry, dont know how to do
