### ISSUE TITLE
container: Erugo

### ISSUE THREAD

**Issue by DeanWard** [ajnart/dcm#4]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

erugo

### Display Name

Erugo

### Description

A powerful, self-hosted file-sharing platform built with PHP and Laravel with a Vue.js frontend. It offers secure, customizable file-transfer capabilities through an elegant user interface, giving you complete control over your data while providing a seamless experience for both senders and recipients.

### Category

Storage

### Tags

File Sharing

### GitHub URL (Optional)

https://github.com/ErugoOSS/Erugo

### Docker Compose Service Definition

```yaml
services:
  app:
    image: wardy784/erugo:latest
    restart: unless-stopped
    volumes:
      - ./erugo-storage:/var/www/html/storage # Use a dedicated folder
    ports:
      - '9998:80'
    networks:
      - erugo

networks:
  erugo:
    driver: bridge
```
