### ISSUE TITLE
bug: Suggest container form won't validate if networks config item exists

### ISSUE THREAD

**Issue by DeanWard** [ajnart/dcm#5]
### Describe the bug

"Docker Compose must use 2 spaces for services and 4 spaces for properties". If I remove the networks section at the end it passes validation.

```
services:
  app:
    image: wardy784/erugo:latest
    restart: unless-stopped
    volumes:
      - ./erugo-storage:/var/www/html/storage # Use a dedicated folder
    ports:
      - '9998:80'
    networks:
      - erugo

networks:
  erugo:
    driver: bridge
```

### Steps to reproduce

1: https://compose.ajnart.dev/templates
2: click on suggest container
3: fill in the form with networks: included

### Impact

Makes it impossible to submit the form

### Browser

Brave

### Operating System

MacOS
