### ISSUE TITLE
container: pinchflat

### ISSUE THREAD

**Issue by mrwhatley** [ajnart/dcm#7]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

pinchflat

### Display Name

pinchflat

### Description

A self-hosted app for downloading YouTube content built using yt-dlp.

### Category

Media

### Tags

TV, PVR, Monitoring

### GitHub URL (Optional)

https://github.com/kieraneglin/pinchflat

### Docker Compose Service Definition

```yaml
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      - TZ=${TZ}
    ports:
      - "8945:8945"
    volumes:
      - ${CONFIG_PATH}/pinchflat:/config
      - ${DATA_PATH}/downloads:/downloads
```
