### ISSUE TITLE
container: pairdrop

### ISSUE THREAD

**Issue by mrwhatley** [ajnart/dcm#8]
### Prerequisites

- [x] I have searched the issues and confirmed this container has not been suggested before
- [x] I have verified the container image is actively maintained
- [x] I have tested this container configuration

### Container ID

pairdrop

### Display Name

pairdrop

### Description

File sharing on your local network that works on all platforms.

### Category

Media

### Tags

Cloud, Sharing

### GitHub URL (Optional)

https://github.com/schlagmichdoch/PairDrop

### Docker Compose Service Definition

```yaml
services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=${PUID} # UID to run the application as
      - PGID=${PGID} # GID to run the application as
      - WS_FALLBACK=${WS_FALLBACK}# Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=${RATE_LIMIT} # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=${RTC_CONFIG} # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=${DEBUG_MODE} # Set to true to debug container and peer connections.
      - TZ=${TZ} # Time Zone
    ports:
      - "3000:3000" # Web UI. Change the port number before the last colon
```
